image: ros:crystal-ros-base

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apt-get update
  - cp 20-default.list /etc/ros/rosdep/sources.list.d/
  - rosdep update
  - rosdep install -y --from-paths . -i .
  - apt install -y python3-colcon-ros
  - git submodule init
  - git submodule update

colcon:
  script:
    - colcon build

agent_ws:
  script:
    - colcon build --packages-select micro_ros_setup
    - . install/local_setup.sh
    - mkdir ros2
    - ros2 run micro_ros_setup create_agent_ws.sh ros2
    - rosdep install --from-paths ros2 -i . -y \
      --skip-keys="rosidl_typesupport_opensplice_c rosidl_typesupport_opensplice_cpp \
        rmw_opensplice_cpp rmw_connext_cpp rosidl_typesupport_connext_c \
        rosidl_typesupport_connext_cpp"
    - colcon build 
