image: ros:crystal-ros-base

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - apt-get update
  - cp 20-default.list /etc/ros/rosdep/sources.list.d/
  - rosdep update
  - rosdep install --from-paths . -i .
  - ln -s . src

colcon:
  - colcon build